/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exampleProject;

import java.util.ArrayList;
import java.util.LinkedList;

    public class App {
        public String getGreeting() {
            return "Hello World!";
        }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        ArrayList<Integer> some_dyn = new ArrayList<>(5);
        some_dyn.add(156);
        some_dyn.add(756);
        some_dyn.add(8);
        some_dyn.add(43);
        some_dyn.add(1);
        some_dyn.add(23);
        some_dyn.add(3);
        
//        some_dyn.clear();
//        System.out.println(some_dyn.size());
        some_dyn.remove(0);
        
        for (Integer x : some_dyn) {
            System.out.println(x);
        }
        
        LinkedList<String> names = new LinkedList<>();
        
        names.add("Igor");
        names.add("Jonh");
        names.add("Tom");
        names.add("Bob");
        names.add("Rob");
        
        names.add(3, "Beka");
        
        for (String x : names) {
            System.out.println(x);
        }
    }
}
